services:
  penpot-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: penpot-mcp:mcp-prod
    ports:
      - "4400:4400"
      - "4401:4401"
      - "4402:4402"
      - "4403:4403"
    environment:
      PENPOT_MCP_SERVER_LISTEN_ADDRESS: 0.0.0.0
      PENPOT_MCP_SERVER_ADDRESS: localhost
      PENPOT_MCP_SERVER_PORT: 4401
      PENPOT_MCP_WEBSOCKET_PORT: 4402
      PENPOT_MCP_REPL_PORT: 4403
      PENPOT_MCP_PLUGIN_SERVER_LISTEN_ADDRESS: 0.0.0.0
      PENPOT_MCP_PLUGIN_PORT: 4400
      PENPOT_MCP_REMOTE_MODE: "true"
      PENPOT_MCP_MULTI_USER_MODE: "true"
      PENPOT_MCP_LOG_LEVEL: info
    volumes:
      - ./logs:/opt/penpot/mcp/logs